### ISSUE TITLE
Deps issues due to major bump of ajv

### ISSUE THREAD

**Issue by majapw** [webpack-contrib/schema-utils#23]
Hello!

Recently https://github.com/webpack-contrib/schema-utils/pull/22 was released as part of a patch update. Unfortunately, bumping a peer dep a major version causes all sorts of deps 🔥s up the tree and my tests are now all failing on `npm ls`.

Can we undo this change and republish as a major? 

@ljharb @gabergg @airbnb/webinfra

**Comment by backwardok** [comment]
as one example, eslint is pegged to version 5: https://github.com/eslint/eslint/blob/master/package.json#L37

**Comment by michael-ciniawsky** [comment]
While `ajv` released a major, for `schema-utils` it's still a `patch` (no breaking changes). What exactly is breaking setups ? Normally `node_modules` should simply contain two versions of `ajv` if other dependencies require different major versions of the package

**Comment by majapw** [comment]
Ahh, you're totally right. I thought that ajv was a peer dep of this package but it is a direct dep. I'm super sorry! This is a problem elsewhere in my tree. :| 

Sorry for the red flag!

**Comment by filipesilva** [comment]
Heya, I'm also looking into this as part of https://github.com/angular/angular-cli/issues/9691 and I'm not too sure what to make of it.

At the moment I think this is a npm bug.

I added a reproduction in https://github.com/filipesilva/ajv-peerdep-issue and reported it in https://github.com/npm/npm/issues/19877.

--- 


# ajv-peerdep-issue

This repo shows a problem with how `npm@5.6.0` hoists dependencies that have peer dependencies.

Running `npm install` will show the following warning:
```
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
```

The following dependencies are relevant:
- this repro itself depends on two packages: `ajv@5.5.2` and `webpack@3.11.0`.
- `webpack@3.11.0` depends on `ajv@^6.1.0` and `ajv-keywords@^3.1.0`.
- `ajv-keywords@3.1.0` has a peer dependency on `ajv@^6.0.0`


When `npm` resolves these dependencies they end up looking like this:
```
ajv-peerdep-issue@1.0.0 D:\sandbox\ajv-peerdep-issue
`-- ajv@5.5.2
`-- ajv-keywords@3.1.0
`-- webpack@3.11.0
  `-- ajv@6.1.0
```

This is a problem because the hoisted `ajv-keywords@3.1.0` will not have its peer dependency on `ajv@^6.0.0` met.
